import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import React from 'react'
import StoreProvider from '@/app/StoreProvider'
import {signIn} from 'next-auth/react'
import {AuthError} from 'next-auth'
import {Button} from 'antd'

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
      <StoreProvider>
          <AntdRegistry>
              {children}
          </AntdRegistry>
      </StoreProvider>
      </body>
    </html>
  );
}
